version: "3"
services:
  backend:
    restart: always
    build: 
      context: './backend'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - sashnevskiy
    ports:
      - "8888:8888"

  frontend:
    restart: always
    build: 
      context: './frontend'
      dockerfile: Dockerfile.prod
    image: "sashnevskiy/current-news:frontend"

    ports:
      - "80:80"
    
    # ports:
    #   - "3000:3000"

    networks:
      - sashnevskiy

  redis:
    image: redis/redis-stack-server #"redis:7.0.7-bullseye"
    restart: always

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
    
    networks:
      - sashnevskiy

    expose:
      - 6379

networks:
  sashnevskiy:
    driver: bridge