version: "3"
services:
  backend:
    restart: always
    image: "sashnevskiy/current-news:backend"
    networks:
      - sashnevskiy
    ports:
      - "8888:8888"

  frontend:
    restart: always
    image: "sashnevskiy/current-news:frontend"

    ports:
      - "80:80"
    
    # ports:
    #   - "3000:3000"

    networks:
      - sashnevskiy

  redis:
    image: "redis:7.0.7-bullseye" #redis/redis-stack-server
    restart: always
    
    networks:
      - sashnevskiy

    expose:
      - 6379

networks:
  sashnevskiy:
    driver: bridge