url:
  "https://newsdata.io/api/1/news"
apiKey:
  "pub_14662fcf3c66110105b27dda083ed10833079"
continent:
  NorthAmerica:
    [ca, us, mx, do, cu]
  Europe:
    [de, fr, it, gb, es]
  Asia:
    [ru, cn, in, kp, kr]
  Africa:
    [za, eg, dz, cm, gh]
  SouthAmerica:
    [ar, br, cl, co, ec]
  Oceania:
    [au, nz]
category:
  [business, politics, sports, science, entertainment] #[] to use all categories